name: devoverflow
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # Updated to a common stable range

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^14.2.0  # For powerful and simple navigation
  flutter_bloc: ^8.1.6 # For state management (Cubit)
  equatable: ^2.0.5    # To compare objects, used with BLoC states
  lottie: ^3.1.0
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sounds/
    - assets/dev.json

  # To add custom fonts, you can add them here.
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #   - family: Fira Code
  #     fonts:
  #       - asset: assets/fonts/FiraCode-Regular.ttf
