name: Android CI - Build debug APK

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: |
          flutter channel stable
          flutter upgrade --force
          flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug --no-shrink

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: devoverflow-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
